# Welcome to Jekyll!
#
# If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.

# Site settings
title: John D Pell
author: John D Pell
email: John@Pell.cc
description: >- # this means to ignore newlines until "baseurl:"
  Enterprise security is just operational excellence in action.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jdp.cx" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gaelicWizard
github_username:  gaelicWizard
linkedin_username: gaelicWizard
google_analytics: G-3B8KRF0H7B
microsoft_mcid: 16599973
vmware_certifee: VMW-01381449L-00454924

collections:
  jobs:
    sort_by: endDate
  clients:
    sort_by: endDate
  projects:
    sort_by: date
  degrees:
    sort_by: date
  certifications:
    sort_by: date
  prospects:
    sort_by: date
    output: true
    permalink: /:name

# Build settings
markdown: kramdown
theme: jekyll-theme-time-machine
plugins:
#  - jekyll-feed

kramdown:
  parse_block_html: true

page_excerpts: true # first paragraph is available as a variable
